services:
  auction-db:
    container_name: auction-db
    image: postgres:14.4
    env_file:
      - .env
    ports:
      - 2000:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  auction-pgadmin:
    container_name: auction-pgadmin
    image: dpage/pgadmin4:6.12
    env_file:
      - .env
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - auction-db
volumes:
  postgres:
  pgadmin: